### PR TITLE
TASK: provide user documentation

### PR DESCRIPTION
**Pull request by gerhard-boden**
This is the first draft for the user documentation.

The Neos parts of the documentation can be found here: 
https://github.com/dfeyer/neos-development-collection/pull/6

### CODE REVIEW

**Comment by dfeyer** [comment]
Thanks @gerhard-boden the documentation about the Neos side of this project need to go to the Neos Adapater, where we can explain how to install and configure it (redirect codes, storage, ...). Can you remove the Neos parts from this PR and push an other on for the Neos package ? Or maybe directly in the Neos main documentation.

@aertmann @kitsunet What did you think, better to have the document in the Neos package for more visibility ?

**Comment by gerhard-boden** [comment]
Thanks for the feedback! 

I'm not a huge fan of splitting the documentation in half, maybe we could just leave out the Neos part for the Flow documentation while leave the Flow parts in for the Neos Documentation (since Neos users need the flow commands also). But duplicating text would make updating the documentation more complex.

Maybe linking both parts of the documentation will be enough?

When a decision has been made I will move or split the documentation accordingly.

**Comment by dfeyer** [comment]
I'm not enough in the documentation topic currently, @gerhard-boden can you check with the guys from the documentation guild on Slack to see what they think about this ? Don't know is we have a possibility to create crosslink between documentation. If it's possible, i fine by having the Flow document in Flow and the Neos documentation in Neos with cross link between both.

Maybe @aertmann has more detail about this ?

**Comment by dfeyer** [comment]
@gerhard-boden In the last version of the PR i improve greatly the redirection:add cli command, you should update the documentation. And I also introduce a redirection:list with regexp matching that deserve some documentation. 

A thanks a lots for help on the documentation topic

**Comment by gerhard-boden** [comment]
@dfeyer I've restructured/rewritten most of the command documentation to make it more suitable for the `Command Reference` section.
http://neos.readthedocs.org/en/stable/References/CommandReference.html

Haven't pushed anything yet, since I must proof read it tomorrow.

After the text for the documentation is final and most of your code changes are done, I will open a PR where I replace all the documentation comment lines within the `CommandController`, so the `Command.rst` will be autogenerated for the mos part from the code. I'm not sure if that is mandatory though (will ask again in the channel before I go through with it).

Thanks again for all your hard work!

**Comment by aertmann** [comment]
@gerhard-boden: not exactly sure what you're mean, but if it's auto generated then it needs to come from the controller.. otherwise it will just be overwritten later on

**Comment by gerhard-boden** [comment]
@aertmann 
I mean documentation like
https://raw.githubusercontent.com/neos/neos-development-collection/2.1/TYPO3.Neos/Documentation/References/CommandReference.rst

that is generated from comments like https://github.com/neos/neos-development-collection/blob/2.1/TYPO3.Media/Classes/TYPO3/Media/Command/MediaCommandController.php#L127-L135

My actual question was if we have to autogenerate the CommandReference from comments or if we can write it on our own.

**Comment by gerhard-boden** [comment]
Today I pushed the documentation i wrote 2 days ago.

Like said before we might have to move the text from the `.rst` to the code comments. But I think it's easier to review in the current state, since this is what will look like when autogenerated later.

Here you can find the Neos part https://github.com/dfeyer/neos-development-collection/pull/6 that was removed from this documentation.

**Comment by dfeyer** [comment]
Will review this soonish, thanks

**Comment by dfeyer** [comment]
@gerhard-boden NIce, maybe we need to explain that the league/csv package is optional, and need to be installed for the import/export stuff to work

Did we need some documentation regarding the RedirectStorageInterface to help user build their own RedriectStorage implementation ?

If the Documentation stay in this package we also need to `conf.py` and `Makefile`

**Comment by gerhard-boden** [comment]
Thanks for your feedback!
Added the information about the `league/csv` dependency, 

The documentation for the `RedirectStorageInterface` should be covered as seperate developer guide, since this part of the documentation covers the basic commands and is therefore more end user centric.

I'm not sure if we need the developer guide right away for the initial release, but definitely something useful to keep in mind.

**Comment by aertmann** [comment]
Moved to https://github.com/neos/flow-development-collection/pull/337

**Pull request closed without merging**
